name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            binary: calctokens
          - runs-on: macos-latest
            binary: calctokens-macos-arm64
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo clean --release && cargo build --release
      - name: Create Release & Upload
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/${{ matrix.binary }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
